language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build/
  on:
    branch: main